function SecondaryTable({activatedList}){
    return(<table>
        <thead>
          <tr>
            <th>Tooth</th>
            <th>Upper Eruption (years)</th>
            <th>Lower Eruption (years)</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>CI</td>
            <td>7–8</td>
            <td>6–7</td>
          </tr>
          <tr>
            <td>LI</td>
            <td>8–9</td>
            <td>7–8</td>
          </tr>
          <tr>
            <td>1M</td>
            <td>9–10</td>
            <td>6–7</td>
          </tr>
          <tr>
            <td>1P</td>
            <td>10–11</td>
            <td>10–12</td>
          </tr>
          <tr>
            <td>2P</td>
            <td>10–12</td>
            <td>11–12</td>
          </tr>
          <tr>
            <td>C</td>
            <td>11–12</td>
            <td>9–10</td>
          </tr>
          <tr>
            <td>2M</td>
            <td>12–13</td>
            <td>11–13</td>
          </tr>
          <tr>
            <td>3M</td>
            <td>17–21</td>
            <td>17–21</td>
          </tr>
        </tbody>
      </table>);
}
